# Generated by Django 5.2 on 2025-04-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
